import "../globals.css";

import { Analytics } from "@vercel/analytics/next";
import { SpeedInsights } from "@vercel/speed-insights/next";
import type { Metadata } from "next";
import dynamic from "next/dynamic";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "sonner";

import { AppProviders } from "@/providers/app-providers";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Open Next",
  description: "Generated by Matías Carrera",
};

export default async function LocaleLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  const { locale } = params;
  const messages = (await import(`@/messages/${locale}.json`)).default;

  const CrispWithNoSSR = dynamic(() => import("../../components/crisp"));

  return (
    <html lang={locale}>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AppProviders locale={locale} messages={messages}>
          {children}
          <Toaster position="top-right" richColors />
          <Analytics />
          <SpeedInsights />
          <CrispWithNoSSR />
        </AppProviders>
      </body>
    </html>
  );
}
